# Generated by Django 4.1.7 on 2023-04-30 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcraftapp', '0005_artist_work_artist_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_artist_work',
            fields=[
                ('artist_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_work_id', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_login_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_order_artist_work',
            },
        ),
        migrations.CreateModel(
            name='order_raw_materials',
            fields=[
                ('raw_materials_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_materials_id', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('artist_login_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_order_raw_materials',
            },
        ),
        migrations.AddField(
            model_name='artist_work',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist_work',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raw_materials',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raw_materials',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
