# Generated by Django 4.1.7 on 2023-04-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcraftapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist_register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.IntegerField()),
                ('Name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.TextField()),
            ],
            options={
                'db_table': 'tbl_artist',
            },
        ),
    ]
