# Generated by Django 4.1.7 on 2023-04-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcraftapp', '0002_artist_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='raw_materials',
            fields=[
                ('raw_materials_id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_materials', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_raw_materials',
            },
        ),
    ]
