# Generated by Django 4.1.7 on 2023-04-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcraftapp', '0003_raw_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist_work',
            fields=[
                ('artist_work_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_work', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_artist_work',
            },
        ),
    ]
