# Generated by Django 4.1.7 on 2023-04-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcraftapp', '0004_artist_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist_work',
            name='artist_login_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
