# Generated by Django 4.1.7 on 2023-05-01 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcraftapp', '0006_order_artist_work_order_raw_materials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_work_id', models.IntegerField()),
                ('status', models.TextField()),
                ('entry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_login_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_work_comment',
            },
        ),
    ]
