# Generated by Django 4.1.7 on 2023-05-01 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artcraftapp', '0007_work_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_comment',
            old_name='status',
            new_name='comment',
        ),
    ]
